site_name: DS Contest Tools

nav:
  - Home: index.md
  - Guia de Uso:
    - 'Visão Geral': 'overview.md'
    - 'Instalação': 'installation.md'
    - 'Comandos': 'commands.md'
  - Sobre:
    - 'Licença': 'license.md'
    - 'Notas de versão': 'release-notes.md'
    - 'Contribuindo': 'contributing.md'
  - Desenvolvimento:
    - 'Documentação': 'documentation.md'

theme:
  name: readthedocs
  highlightjs: true
  locale: pt_BR
