[build-system]
requires = ["setuptools>=68.0.0", "setuptools-scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ds-contest-tools"
dynamic = ["version"]
description = "Tools for contest and competitive problems preparation."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Daniel Saad Nogueira Nunes", email = "daniel.nunes@ifb.edu.br" },
]
maintainers = [
    { name = "Matheus Loiola Pinto Curado Silva", email = "matheusloiolapinto@gmail.com" },
    { name = "Leonam Knupp", email = "leonamknupp@hotmail.com" },
]
keywords = ["contest", "competitive programming", "tools"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: Unix",
]
dependencies = ["requests", "psutil"]


[project.scripts]
dscontest = "ds_contest_tools:main"

[project.urls]
repository = "https://github.com/danielsaad/ds-contest-tools/"
documentation = "https://danielsaad.com/ds-contest-tools/"

[tool.setuptools_scm]
tag_regex = "^v(?P<version>.*)$"
write_to = "ds_contest_tools/_version.py"
