import os

from typing import TYPE_CHECKING
from ds_contest_tools.enumarate.problem_answer import ProblemAnswer
from ds_contest_tools.models.statistics import Statistic
from ds_contest_tools.metadata import Paths

if TYPE_CHECKING:
    from ds_contest_tools.models.problem import Problem


class Solution:
    """
    Represents a solution to a programming problem.

    Attributes:
        solution_name: The name of the solution file.
        expected_result: The expected result of running the solution.
        output_path: The path to the folder where the output files generated 
        solution_status: The status of the solution.
        statistics: The statistics of a given solution.
        exec_args: The command line arguments to be executed.
        tests: The dictionary of tests that were run on the solution.

    """

    def __init__(self, solution_name: str, expected_result: str, problem_folder: str) -> None:
        """
        Initializes a new instance of the Solution class.

        Args:
            solution_name: The name of the solution file.
            expected_result: The expected result of running the solution.

        """
        self.__solution_name: str = solution_name
        self.__expected_result: str = expected_result
        self.__solution_exec_file_path: str = self.set_solution_file_path(
            problem_folder)
        self.__vm_memory_usage: float = self.__measure_vm_usage()
        self.__output_path: str = self.__generate_output_folder()
        self.__solution_status: ProblemAnswer = None
        self.__statistics: Statistic = None
        self.__exec_args: list = None
        self.__tests: dict = {}

    @property
    def solution_name(self) -> str:
        """
        Gets the name of the solution file.

        Returns:
            str: The name of the solution file.

        """
        return self.__solution_name

    @property
    def expected_result(self) -> str:
        """
        Gets the expected result of running the solution.

        Returns:
            str: The expected result of running the solution.

        """
        return self.__expected_result

    @property
    def solution_exec_file_path(self) -> str:
        """
        Gets the path to the solution executable file.

        Returns:
            str: The path to the solution executable file.
        """
        return self.__solution_exec_file_path

    @property
    def vm_memory_usage(self) -> float:
        """
        Gets the memory usage of the solution in bytes.

        Returns:
            float: The memory usage of the solution in bytes.
        """
        return self.__vm_memory_usage

    @property
    def output_path(self) -> str:
        """
        Gets the path to the folder where the output files generated by the 
            solution are stored.

        Returns:
            The path to the folder where the output files generated by the
              solution are stored.

        """
        return self.__output_path

    @property
    def solution_status(self) -> ProblemAnswer:
        """
        Gets the status of the solution.

        Returns:
            Status: The status of the solution.
        """
        return self.__solution_status

    @solution_status.setter
    def solution_status(self, solution_status: ProblemAnswer) -> None:
        """
        Sets the solution status of the test case.

        Args:
            solution_status: The solution status to set.
        """
        self.__solution_status = solution_status

    @property
    def statistics(self) -> 'Statistic':
        """
        Gets the statistics (max execution time, max memory usage...) 
        of the solution

        Returns:
            Statistic: The statistics of the solution
        """
        return self.__statistics

    @statistics.setter
    def statistics(self, statistics: 'Statistic') -> None:
        """
        Sets the statistics information for a given problem

        Args:
            statistics: The statistics information to set
        """
        self.__statistics = statistics

    @property
    def exec_args(self) -> list:
        """
        Gets the command line arguments to be executed

        Returns:
            list: A list of the arguments
        """
        return self.__exec_args

    @exec_args.setter
    def exec_args(self, exec_args: str) -> None:
        """
        Sets the command line arguments

        Args:
            exec_args: A string of line arguments divided by spaces
        """
        self.__exec_args = [exec_args]

    @property
    def tests(self) -> dict:
        """
        Gets the dictionary of tests that were run on the solution.

        Returns:
            dict: The dictionary of tests that were run on the solution.
        """
        return self.__tests

    def set_solution_file_path(self, problem_folder: str) -> str:
        ext: str = self.get_file_extension()
        binary_file: str = self.get_binary_name()
        file_path: str = ''

        if ext == 'py':
            src_folder: str = os.path.join(problem_folder, 'src')
            file_path = os.path.join(
                src_folder, binary_file)
        else:
            bin_folder: str = os.path.join(problem_folder, 'bin')
            file_path = os.path.join(
                bin_folder, binary_file)

        return file_path

    def add_tests(self, tests: dict) -> None:
        """
        Adds a dictionary of tests to the dictionary of tests that were run 
            on the solution.

        Args:
            test: The dictionary with the tests to add.
        """
        self.__tests = tests

    def get_binary_name(self) -> str:
        """
        Returns the name of the binary file generated from the solution.

        Args:
            solution_name: The name of the solution file.

        Returns:
            str: The name of the binary file generated from the solution.
        """
        file_name, _ = os.path.splitext(self.__solution_name)
        return file_name

    def get_file_extension(self) -> str:
        """
        Returns the extension of the solution file.

        Args:
            solution_name: The name of the solution file.

        Returns:
            str: The extension of the solution file.
        """
        _, ext = os.path.splitext(self.__solution_name)
        return ext.replace('.', '')

    def get_binary_file_path(self) -> str:
        """
        Returns the path to the binary file generated from the solution.

        Returns:
            str: The path to the binary file generated from the solution.
        """
        return os.path.join(Paths().get_problem_dir, 'bin', self.get_binary_name())

    def get_source_file_path(self, problem_obj: 'Problem') -> str:
        """
        Returns the path to the source file of the solution.

        Returns:
            str: The path to the source file of the solution.
        """
        return os.path.join(problem_obj.problem_dir, 'src', self.solution_name)

    def __generate_output_folder(self) -> str:
        """
        Returns the path to the folder where the output files generated by the solution are stored.

        Returns:
            str: The path to the folder where the output files generated by the solution are stored.
        """
        root_tmp_path: str = Paths().get_tmp_output_dir()
        output_folder: str = os.path.join(
            root_tmp_path, self.get_file_extension(), self.get_binary_name())
        return output_folder

    def __execute_command(self, pid, memory_used, exec_args: list[str]) -> str:
        """
        Executes a command on the terminal and returns the output.

        Args:
            pid (Queue): The process id of the executed command.
            memory_used (Value): The memory used by the executed command.
            exec_args (list[str]): The command to execute.


        Returns:
            str: The output of the command.
        """
        from multiprocessing import Pipe
        import subprocess

        conn_sender, conn_recv = Pipe()
        memory_info: tuple = (0, 0)
        p: subprocess.Popen = subprocess.Popen(exec_args)
        pid.put([p.pid, conn_sender])
        try:
            p.communicate(timeout=0.2)
        except subprocess.TimeoutExpired:
            p.kill()
            p.communicate()
        finally:
            memory_info = conn_recv.recv()
        conn_sender.close()
        conn_recv.close()

        memory_used.value = memory_info[0]
        return

    def __measure_vm_usage(self) -> int:
        """
        Returns the memory usage of the solution in Megabytes.

        Returns:
            int: The memory usage of the solution in Megabytes.
        """
        from math import inf
        from ds_contest_tools.checker import memory_monitor
        from multiprocessing import Process, Event, Manager, Queue, Value

        ext: str = self.get_file_extension()
        exec_args: list[str] = list()
        memory_used: Value = Value('i', 0)
        if ext == 'c' or ext == 'cpp':
            return memory_used.value

        elif ext == 'py':
            from ds_contest_tools.config import PYTHON3_INTERPRETER, PYTHON_VM_MEMORY_TEST_FILE_PATH

            exec_args = [PYTHON3_INTERPRETER,
                         PYTHON_VM_MEMORY_TEST_FILE_PATH]

        elif ext == 'java':
            from ds_contest_tools.config import JAVA_INTERPRETER, JAVA_FLAG, JAVA_VM_MEMORY_TEST_FOLDER, JAVA_VM_TEST_FILE
            exec_args = [JAVA_INTERPRETER, JAVA_FLAG,
                         JAVA_VM_MEMORY_TEST_FOLDER, JAVA_VM_TEST_FILE]

        with Manager() as manager:
            pid: Queue = manager.Queue(maxsize=1)
            stop_monitor: Event = manager.Event()
            monitor_process = Process(target=memory_monitor, args=(
                pid, inf, stop_monitor))
            monitor_process.start()
            process: Process = Process(target=self.__execute_command, args=(
                pid, memory_used, exec_args))
            process.start()
            process.join()
            stop_monitor.set()
            monitor_process.join()

        return memory_used.value